Repository NASA-AMMOS/seq-json-schema, pull requests merged in 2023-02, with the labels that each got.

#3 Update schema args as objects
  package-lock.json
  package.json
  schema.json
  setup.py
  test/invalid-seq-json/activate-extra-property.seq.json
  test/invalid-seq-json/activate-missing-sequence.seq.json
  test/invalid-seq-json/activate-missing-time.seq.json
  test/invalid-seq-json/activate-missing-type.seq.json
  test/invalid-seq-json/activate-noninteger-engine.seq.json
  test/invalid-seq-json/activate-nonstring-epoch.seq.json
  test/invalid-seq-json/activate-nonstring-sequence.seq.json
  test/invalid-seq-json/args-invalid-type.seq.json
  test/invalid-seq-json/command-extra-property.seq.json
  test/invalid-seq-json/command-missing-stem.seq.json
  test/invalid-seq-json/command-missing-time.seq.json
  test/invalid-seq-json/command-missing-type.seq.json
  test/invalid-seq-json/command-nonarray-models.seq.json
  test/invalid-seq-json/command-nonstring-stem.seq.json
  test/invalid-seq-json/ground-block-extra-property.seq.json
  test/invalid-seq-json/ground-block-missing-name.seq.json
  test/invalid-seq-json/ground-block-missing-time.seq.json
  test/invalid-seq-json/ground-block-missing-type.seq.json
  test/invalid-seq-json/ground-block-nonarray-models.seq.json
  test/invalid-seq-json/ground-block-nonstring-name.seq.json
  test/invalid-seq-json/ground-event-extra-property.seq.json
  test/invalid-seq-json/ground-event-missing-name.seq.json
  test/invalid-seq-json/ground-event-missing-time.seq.json
  test/invalid-seq-json/ground-event-missing-type.seq.json
  test/invalid-seq-json/ground-event-nonarray-models.seq.json
  test/invalid-seq-json/ground-event-nonstring-name.seq.json
  test/invalid-seq-json/nonstring-description.seq.json
  test/invalid-seq-json/time-extra-property.seq.json
  test/invalid-seq-json/time-missing-type.seq.json
  test/invalid-seq-json/time-nonenum-type.seq.json
  test/invalid-seq-json/time-nonstring-tag.seq.json
  test/valid-seq-json/activate.seq.json
  test/valid-seq-json/all-possible-fields.seq.json
  test/valid-seq-json/command.seq.json
  test/valid-seq-json/example-seq-ieee.seq.json
  test/valid-seq-json/ground-block.seq.json
  test/valid-seq-json/ground-event.seq.json
  test/valid-seq-json/load.seq.json
  test/valid-seq-json/metadata.seq.json
  test/valid-seq-json/rtc.seq.json
  test/valid-seq-json/steps-and-requests.seq.json
  types.ts
Labels: refactor, breaking change

#4 Added repeat args, included them in the all-possible-fields test
  package-lock.json
  package.json
  schema.json
  setup.py
  test/invalid-seq-json/variable-argument-repeat-missing-tag.json
  test/valid-seq-json/all-possible-fields.seq.json
  types.ts
Labels: refactor, breaking change

#5 Add Python tests
  .github/workflows/test.yml
  test/test.py
Labels: test, ci

#7 Upgrade JSON schema to 2020-12
  package-lock.json
  package.json
  schema.json
  setup.py
  test/test.js
Labels: refactor

#10 Repeat arg fixes
  package-lock.json
  package.json
  schema.json
  setup.py
  test/invalid-seq-json/nested-repeat-arg.seq.json
  test/valid-seq-json/all-possible-fields.seq.json
  types.ts
Labels: refactor, breaking change
